// firebase_options.dart
// !! IMPORTANT !!
// This file is generated by the FlutterFire CLI.
// DO NOT EDIT MANUALLY.
//
// Run `flutterfire configure` in your project directory to generate this file.
// See: [https://firebase.google.com/docs/flutter/setup](https://firebase.google.com/docs/flutter/setup)

// Example structure (replace with your actual generated content):
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
 static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // --- REPLACE WITH YOUR WEB CONFIG ---
      return const FirebaseOptions(
        apiKey: 'AIzaSyCfD9Mn8xI2UgQ9900zg7WbSXmjEPwTxNU',
        appId: '1:387671815228:web:2971791089e25cbd20bf39',
        messagingSenderId: '387671815228',
        projectId: 'financeiro-77fb2',
        authDomain: 'financeiro-77fb2.firebaseapp.com',
        storageBucket: 'financeiro-77fb2.firebasestorage.app',
        // measurementId: 'YOUR_MEASUREMENT_ID', // Optional
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
         // --- REPLACE WITH YOUR ANDROID CONFIG ---
        return const FirebaseOptions(
          apiKey: 'AIzaSyCB9fKsJS4-VxRdd6Syb6PwAtmtgDInO58',
          appId: '1:387671815228:android:9f2e813913ce70f920bf39',
          messagingSenderId: '387671815228',
          projectId: 'financeiro-77fb2',
          storageBucket: 'financeiro-77fb2.firebasestorage.app',
        );
      case TargetPlatform.iOS:
        // --- REPLACE WITH YOUR IOS CONFIG ---
        // return const FirebaseOptions(
        //   apiKey: 'YOUR_IOS_API_KEY',
        //   appId: 'YOUR_IOS_APP_ID',
        //   messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
        //   projectId: 'YOUR_PROJECT_ID',
        //   storageBucket: 'YOUR_PROJECT_ID.appspot.com',
        //   iosBundleId: 'YOUR_IOS_BUNDLE_ID',
        // );
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // Add cases for other platforms (macOS, Windows, Linux) if needed
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}